import React from 'react'
import './globals.css'
import Header from '@/components/Header';
import AuthState from "@/context/auth/authState";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({children}) {
  console.log('desde layout')

  return (
    <html lang="en">
  
      <title>ReactNodeSend</title>
       <body>
          <div className="bg-gray-100 min-h-screen">
            <div className="container mx-auto">
              <Header/>
                <main className="mt-20">
            
                  {children}
                
                </main>
            </div>
            
          </div>
        </body>
    </html> 
    
  
  );
}

// import React from 'react'
// import AuthState from "@/context/auth/authState";

// const MyApp = ({Component, pageProps}) => {
//     return(
//         <AuthState>
          
//         </AuthState>
//     )
// }
// export default MyApp